const menu = [
    {
      id: 1,
      title: 'San-Andreas Theme',
      category: 'Games',
      img: './images/item-1.jpg',
      audio: './images/item-1.mp3',
      desc: `Theme song of GTA san-andreas game `,
      number: '1x',
    },
    {
      id: 2,
      title: 'Itatchi-theme',
      category: 'Anime',
      img: './images/item-2.jpg',
      audio: './images/item-2.mp3',
      desc: `Soundtrack from a famous Japanese Anime `,
      number: '2x',
    },
    {
      id: 3,
      title: 'Hoohah',
      category: 'EDM',
      img: './images/item-3.jpg',
      audio: './images/Fox Stevenson & Curbi - Hoohah.mp3',
      desc: `EDM tract by fox stevenson & Curbi `,
      number: '3x',
    },
    {
      id: 4,
      title: 'Unravel',
      category: 'Anime',
      img: './images/item-4.jpg',
      audio: './images/Unravel - Tokyo Ghoul OP [Piano].mp3',
      desc: `Tokyo Ghoul Theme song `,
      number: '4x',
    },
    {
      id: 5,
      title: 'Faded - Alan Walker',
      category: 'EDM',
      img: './images/item-5.jpg',
      audio: './images/01 Faded.mp3',
      desc: `EDM tract by Alan Walker `,
      number: '5x',
    },
    {
      id: 6,
      title: 'See you again - Charlie Puth',
      category: 'Hip-Hop',
      img: './images/item-6.jpg',
      audio: './images/Wiz_Khalifa_Feat_Charlie_Puth_-_See_You_Again.mp3',
      desc: `Famous song by singer Charlie Puth and Wiz Kalifa in the movie Fast and Furious `,
      number: '6x',
    },
    {
      id: 7,
      title: 'When i grow up - NF',
      category: 'Rock',
      img: './images/item-7.jpg',
      audio: './images/08 When I Grow Up - (SongsLover.com).mp3',
      desc: `Famous rap song by singer NF `,
      number: '7x',
    },
    {
      id: 8,
      title: 'Believer - Imagine Dragons',
      category: 'Rock',
      img: './images/item-8.jpg',
      audio: './images/09. Imagine Dragons - Believer.mp3',
      desc: `Song by a rock band 'Imagine Dragons' `,
      number: '8x',
    },
    {
      id: 9,
      title: 'Radioactive - Imagine Dragons',
      category: 'Rock',
      img: './images/item-9.jpg',
      audio: './images/01 - radioactive(2).mp3',
      desc: `Song by a rock band 'Imagine Dragons' `,
      number: '9x',
    },
    {
      id: 10,
      title: 'Wake me up - Avicii',
      category: 'EDM',
      img: './images/item-10.jpg',
      audio: './images/[1997] avicii - wake me up (cut).mp3',
      desc: `EDM tract by fox stevenson & Curbi `,
      number: '10x',
    },
    {
      id: 11,
      title: 'Sweet child O Mine - Guns N Roses',
      category: 'Jazz',
      img: './images/item-11.jpg',
      audio: './images/Guns_N_Roses_-_Sweet_Child_O_Mine.mp3',
      desc: `Famous song from an American Rock band in 80s' `,
      number: '11x',
    },
    {
      id: 12,
      title: 'KillShot - Eminem',
      category: 'Hip-Hop',
      img: './images/item-12.jpg',
      audio: './images/Eminem_-_Killshot_.mp3',
      desc: `Diss Rap by Rap god Eminem `,
      number: '12x',
    },
  {
      id: 13,
      title: 'Super Coooll',
      category: 'Jazz',
      img: './images/item-13.jpg',
      audio: './images/Eminem_-_Killshot_.mp3',
      desc: `YOLO`,
      number: '13x',
    },
    {
      id: 14,
      title: 'Watever it takes',
      category: 'Hip-Hop',
      img: './images/item-14.jpg',
      audio: './images/Whatever it takes.mp3',
      desc: `Do it anyway `,
      number: '14x',
    },
    {
      id: 15,
      title: 'Drag ME Down',
      category: 'EDM',
      img: './images/item-15.jpg',
      audio: './images/Drag Me Down - One Direction.mp3',
      desc: `Can't get over enough`,
      number: '15x',
    },
    {
      id: 16,
      title: 'One Way Or Another',
      category: 'Jazz',
      img: './images/item-16.jpg',
      audio: './images/one way or another.mp3',
      desc: `Get a Way With This `,
      number: '16x',
    },
    {
      id: 17,
      title: 'Night Changes',
      category: 'Hip-Hop',
      img: './images/item-17.jpg',
      audio: './images/One+Direction+Night+Changes.mp3',
      desc: `Friends Song`,
      number: '17x',
    },
    {
      id: 18,
      title: 'Dusk To Dawn',
      category: 'Anime',
      img: './images/item-18.jpg',
      audio: './images/Zayn+Dusk+Till+Dawn+ft+Sia+Official+Music+Video.mp3',
      desc: `Enjoy The Dayyyy`,
      number: '18x',
    },
    {
      id: 19,
      title: 'I Knew You Were Trouble',
      category: 'Jazz',
      img: './images/item-19.jpg',
      audio: './images/Taylor_Swift_-_I_Knew_You_Were_Trouble.mp3',
      desc: `The Trouble song`,
      number: '19x',
    },
    {
      id: 20,
      title: 'Soak',
      category:'Anime',
      img: './images/item-20.jpg',
      audio: './images/Blank Space - Taylor Swift.mp3',
      desc: `The Power Song`,
      number: '20x',
    },
    {
      id: 21,
      title: 'Idea Behind',
      category:'Rock',
      img: './images/item-21.jpg',
      audio: './images/Imagine Dragons - Believer.mp3',
      desc: `Think Of a Thought `,
      number: '21x',
    },
    {
      id: 22,
      title: 'PlayToWin',
      category:'Anime',
      img: './images/item-22.jpg',
      audio: './images/whatever it takes.mp3',
      desc: `Game To Play `,
      number: '22x',
    },
    {
      id: 23,
      title: 'Style Statement',
      category:'Games',
      img: './images/item-23.jpg',
      audio: './images/When I Grow Up.mp3',
      desc: `Rockyyyy `,
      number: '23x',
    },
    {
      id: 24,
      title: 'Whomsoever',
      category:'Games',
      img: './images/item-24.jpg',
      audio: './images/Drag Me Down.mp3',
      desc: `Enjoy The Beat`,
      number: '24x',
    },
    {
      id: 25,
      title: 'Silly',
      category:'Games',
      img: './images/item-25.png',
      audio: './images/scared.mp3',
      desc: `Must Be Silly `,
      number: '25x',
    },
    {
      id: 26,
      title: 'YOOOOOOOOYOOOO',
      category:'Games',
      img: './images/item-26.jpg',
      audio: './images/Whatever it takes.mp3',
      desc: ` The YOOOO Song `,
      number: '26x',
    }
  ];
  export default menu;